dist: xenial
sudo: required
env:
  global:
  - CHANGE_MINIKUBE_NONE_USER=true
cache:
  directories:
  - tmp/cache
services:
- docker
language: go
go:
- "1.11"
virtualenv:
  system_site_packages: true
addons:
  apt:
    sources:
    - sourceline: deb http://ppa.launchpad.net/longsleep/golang-backports/ubuntu xenial
          main
      key_url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xF6BC817356A3D45E
    packages:
    - docker-ce
    - socat
    - ebtables
before_install:
- sudo docker run -d -it --name nsenter ubuntu:16.04 bash && sudo docker cp nsenter:/usr/bin/nsenter /usr/local/bin/nsenter && sudo docker rm -f nsenter
- curl -Lo ./scripts/install-minikube.sh https://raw.githubusercontent.com/openpitrix/openpitrix/v0.4.1/deploy/kubernetes/scripts/install-minikube.sh
- bash ./scripts/install-minikube.sh
- curl -Lo ./scripts/init-helm.sh https://raw.githubusercontent.com/openpitrix/openpitrix/v0.4.1/deploy/kubernetes/scripts/init-helm.sh
- bash ./scripts/init-helm.sh
install:
- sudo apt-get install -y python-pip
- sudo pip install pybars3
- ./scripts/generate-values.sh -t
- ./scripts/deploy-openpitrix.sh
script:
- ./scripts/test-openpitrix.sh
before_deploy:
- ./scripts/generate-values.sh
- tar -zcvf openpitrix-helm-chart-$TRAVIS_TAG.tar.gz openpitrix
deploy:
  overwrite: true
  provider: releases
  api_key:
    secure: dpKAdpQB1d2Nlt4Ysyit5SZeiNyfjA/An0eBok03wyfm4hDQxdu+RXubMtnZQDtwWetFkBwrMDy530LIOr8t7NSJbgtaOfFuAGUaoo/D1w71f6XhUVPgbknMGS6t+EQNjxqVFHpIdOTcNY/U0NaDAbpxb7Nx75QmsJkePVBhv9wPuP2T0eppoJbvsE6426wHeV5BN4S5bTjD5w0cazNkNdQc0Q2AuUYkOrvGTPY76jEWiBNOnIH9hdCB+X6PKh+Rzuq7vQSbjZr6d9ql+ug7PwxTMLrmWINs64+jHEVPVLzoMPQvbHmsftYjndaCHGlVK6YMGow5O4gwySVOAyLm6p+4nFciTEIUETd6zB/eTzeFXY5P/QztDN6nsAWcQfGp5SnKmIT+UJFqTKmsjcVEv9fZMqpZfsmi77DeV977bV5wKREl15HbMre8R8KI1DXosH6PJ1BBxtpGFgbiLXk7uSoYwKwzewnF0y0v1UpNadjdZ38Ayg/i+0SwMzSZS0XpXyGYoLABNoFG5AcGQPDTrqYmJWCrViZQQss6yUuOJU9toiLqjXfn092gEUXoqdYKsH6wNABNVZX/OtCGkNBU2fPfk0uKoOUb57zZD3+1bwr0OJ00AktNnBBBIQS91MypwbbQ+X1lyNfgnb32inlDV97gKcR2MazO3206R/i4pjk=
  file: openpitrix-helm-chart-$TRAVIS_TAG.tar.gz
  skip_cleanup: true
  on:
    repo: openpitrix/helm-chart
    tags: true
